### ISSUE TITLE
Login Functionality

### ISSUE THREAD

**Issue by MarcusWilder** [MarcusWilder/open-evaluation#5]

**Comment by GalMunGral** [comment]
I did some research on this last week. So apparently Georgia Tech uses the [CAS (Central Authentication Service) protocol](https://apereo.github.io/cas/5.1.x/protocol/CAS-Protocol.html) for GT Login Service [[source]](https://drupal.gatech.edu/handbook/user-authentication-authorization). 
## How it works
The Georgia Tech CAS server is located at `login.gatech.edu`. The authentication flow is kind of similar to OAuth 2.0 (Facebook login, etc.) : Suppose the URL of the landing page of the hypothetical web app is `https://www.gatech.edu` (One issue about GT Login Service is that apps that request its service need to be authorized (by OIT I think)). The process is as follows:
1. The user, who is not logged in yet, visits the web app at
```
https://www.gatech.edu
```
2. The app server (`www.gatech.edu`) sees that the user is not logged in (because it didn't receive any tokens in the form of query strings indicating the user's login status), so it redirects the browser to the GT Login page (`login.gatech.edu/cas/login`), passing the URI-encoded app URL (`https%3A%2F%2Fwww.gatech.edu`) as the `service` query parameter so that the CAS server could see which app is requesting the service. The full redirect URL is
```
https://login.gatech.edu/cas/login?service=https%3A%2F%2Fwww.gatech.edu
```
2. The browser now talks to GT Login (CAS) server at `login.gatech.edu`. Once the user finishes the login process (including Duo 2FA, and whatever mechanism that might be integrated into GT Login in the future), The GT Login server redirects the browser back to the app, which is only possible because it was given the app URL as an input (query param) a moment ago. In addition to the app URL, a ticket indicating login success is appended to the redirect URL, which now looks like:
```
https://www.gatech.edu/?ticket=ST-319749-cRFPU5aXBaSI2vg7hLHl-cas-prod5.gatech.edu
```
3.  Now the browser points to `www.gatech.edu` again, but this time it provides the app server with the ticket it just obtained from GT Login, so the app server won't redirect the browser away. Instead it verifies the validity of that ticket by contacting CAS server directly (this time it's entirely in the back end and not through a HTTP redirect. Since the browser is not involved, it is totally unaware of this process). The endpoint on the CAS server the app server talks to is `/serviceValidate`. The app server passes in two pieces of information

    -  Its own identity (URI encoded app URL, same as above): `https%3A%2F%2Fwww.gatech.edu`
    - The ticket it needs to verify: `ST-296296-FNk1Y5CvbnwBuLyIg6fk-cas-prod5.gatech.edu`

The full URL it sends request to is
```
https://login.gatech.edu/cas/serviceValidate?service=https%3A%2F%2Fwww.gatech.edu&ticket=ST-296296-FNk1Y5CvbnwBuLyIg6fk-cas-prod5.gatech.edu
```
4.  Upon successful verification, the CAS server returns the XML
```xml
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
	<cas:authenticationSuccess>
		<cas:user>{{username}}</cas:user>
	</cas:authenticationSuccess>
</cas:serviceResponse>
```
If the CAS server cannot verify the ticket, perhaps because the ticket is forged or has expired, then something like this is returned:
```xml
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
	<cas:authenticationFailure code='INVALID_TICKET'>
		ticket &#039;ST-296296-FNk1Y5CvbnwBuLyIg6fk-cas-prod5.gatech.edu&#039; not recognized
	</cas:authenticationFailure>
</cas:serviceResponse>
```
By parsing the XML response, the app server can determine the login status of the user and set the browser's session cookie.

Here is a diagram from the spec: https://apereo.github.io/cas/5.0.x/protocol/CAS-Protocol.html
![](https://apereo.github.io/cas/5.1.x/images/cas_flow_diagram.png)

## Demo
I implemented this flow in Node.js, up to but not including the issuing session cookies step. Upon login success, it also performs a [LDAP directory lookup](https://webmasters.gatech.edu/handbook/finding-gt-accounts-using-public-ldap-server) for user roles, which may or may not be the best approach. The code is quite messy but it's just for demonstrating the feasibility of the integration. You can clone this demo from `https://github.com/GalMunGral/cas-demo.git`.

A caveat is that because only authorized URLs such as all `*.gatech.edu` URLs are allowed to use GT Login Service, you'll have to type in `http://open-eval.gatech.edu` instead of `http://localhost` or `http://localhost:80`. A rather hacky solution that I used is to edit the [hosts file](https://en.wikipedia.org/wiki/Hosts_(file)) to force your computer to resolve the domain `open-eval.gatech.edu` to `127.0.0.1` (local host). Then if we actually deploy the app to that domain we only need to delete that entry from hosts file and the domain name would then resolve to the actual IP.
